#!/usr/bin/env bash

set -e

# zsh
echo "🎁  zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# run npm things
echo "⛑  npm installing some stuff..."
npm install -g diff-so-fancy
